services:
  - type: web
    name: peluqueria-xtylo-api
    runtime: node
    rootDir: BACK
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: CORS_ORIGIN
        sync: false
